version: 2
updates:
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: nuget
    directory: /src-lhm
    schedule:
      interval: weekly
    groups:
      dotnet-dependencies:
        patterns: ["*"]
        exclude-patterns: ["LibreHardwareMonitorLib"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
